# Generated by Django 6.0.6 on 2026-09-25 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30, verbose_name='цвет')),
            ],
            options={
                'verbose_name': 'цвет',
                'verbose_name_plural': 'цвет',
            },
        ),
        migrations.CreateModel(
            name='Cotegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cotegory', models.CharField(max_length=100, verbose_name='котегория')),
            ],
            options={
                'verbose_name': 'котегория',
                'verbose_name_plural': 'котегория',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='размер')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размер',
            },
        ),
        migrations.CreateModel(
            name='Vidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidi', models.CharField(max_length=100, verbose_name='виды')),
            ],
            options={
                'verbose_name': 'виды',
                'verbose_name_plural': 'виды',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(verbose_name='Slug')),
                ('text', models.TextField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('count', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.PositiveIntegerField(blank=True, default=0, null=True)),
                ('isActive', models.BooleanField(blank=True, default=True, null=True, verbose_name='доступно')),
                ('image', models.ImageField(blank=True, null=True, upload_to='posts/', verbose_name='Фотография')),
                ('cotegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps.cotegory', verbose_name='котегория')),
                ('vidi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apps.vidi', verbose_name='виды')),
            ],
        ),
    ]
